
SELECT TOP 1 GNAME
FROM GAME
JOIN RENT
ON GAME.GID = RENT.GID
GROUP BY GNAME
ORDER BY COUNT(*) DESC



SELECT GNAME 
FROM GAME
WHERE GAME.GID NOT IN (SELECT GID FROM RENT) 
AND MONTH(YEAR) BETWEEN MONTH(GETDATE())-1 AND MONTH(GETDATE());



SELECT TOP 1 CLIENTFNAME
FROM CLIENT
JOIN RENT
ON CLIENT.CLIENTEMAIL = RENT.CLIENTEMAIL
WHERE MONTH(RENTDATE) BETWEEN MONTH(GETDATE())-1 AND MONTH(GETDATE())
GROUP BY CLIENTFNAME
ORDER BY COUNT (*) DESC


SELECT TOP 1 VNAME
FROM GAME
JOIN RENT
ON GAME.GID = RENT.GID
WHERE MONTH(RENTDATE) BETWEEN MONTH(GETDATE())-1 AND MONTH(GETDATE())
GROUP BY VNAME
ORDER BY COUNT (*) DESC


SELECT VNAME 
FROM GAME
WHERE GAME.GID NOT IN (SELECT GID FROM RENT) 
AND MONTH(YEAR) BETWEEN MONTH(GETDATE())-1 AND MONTH(GETDATE());


SELECT VNAME 
FROM GAME
WHERE YEAR(YEAR) NOT LIKE YEAR(GETDATE())-1;

